// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxPvGBLJNDo1DUa3A7Gbm-jmallzMqZdM',
    appId: '1:923146792029:web:7ea30a236a7df1b916b1b4',
    messagingSenderId: '923146792029',
    projectId: 'tareaaplicaciones-7b448',
    authDomain: 'tareaaplicaciones-7b448.firebaseapp.com',
    storageBucket: 'tareaaplicaciones-7b448.firebasestorage.app',
    measurementId: 'G-05VYVN4TGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2vhMe4x3A3uOJabRwYhZ4Dx8OwL2Z1ck',
    appId: '1:923146792029:android:2a22ea085cb4478116b1b4',
    messagingSenderId: '923146792029',
    projectId: 'tareaaplicaciones-7b448',
    storageBucket: 'tareaaplicaciones-7b448.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPNGaRFSvHKWdkdR8WdGw64GFDRg8oRvY',
    appId: '1:923146792029:ios:fb541ed7b11dbe2616b1b4',
    messagingSenderId: '923146792029',
    projectId: 'tareaaplicaciones-7b448',
    storageBucket: 'tareaaplicaciones-7b448.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
